# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "add-a-new-product"
client_id = "803bede970846c16b267de40ef801f6d"
application_url = "https://offer-phases-definitely-dis.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://offer-phases-definitely-dis.trycloudflare.com/auth/callback",
  "https://offer-phases-definitely-dis.trycloudflare.com/auth/shopify/callback",
  "https://offer-phases-definitely-dis.trycloudflare.com/api/auth/callback",
  "https://offer-phases-definitely-dis.trycloudflare.com/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "pialneel.myshopify.com"
